/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Sat Jan 30 2016 17:20:08 GMT-0600 (CST).
 */

define([
    'TemplateCreator/TemplateCreator',
    './JavaGenerator'
], function (
    PluginBase,
    JavaGenerator
) {
    'use strict';

    /**
     * Initializes a new instance of CreateJava.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin CreateJava.
     * @constructor
     */
    var CreateJava = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.generator = new JavaGenerator();
    };

    // Prototypal inheritance from PluginBase.
    CreateJava.prototype = Object.create(PluginBase.prototype);
    CreateJava.prototype.constructor = CreateJava;

    /**
     * Gets the name of the CreateJava.
     * @returns {string} The name of the plugin.
     * @public
     */
    CreateJava.prototype.getName = function () {
        return 'CreateJava';
    };

    /**
     * Gets the semantic version (semver.org) of the CreateJava.
     * @returns {string} The version of the plugin.
     * @public
     */
    CreateJava.prototype.getVersion = function () {
        return '0.1.0';
    };

    return CreateJava;
});
